---
- name: install python mysql bindings
  apt: name=python-mysqldb state=present
  become: yes

- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present

- name: Create mysql user
  mysql_user:
    name={{ wp_mysql_user }}
    password={{ wp_mysql_password }}
    priv=*.*:ALL
    host=%

- name: Update mysql config file
  lineinfile:
    dest=/etc/mysql/mysql.conf.d/mysqld.cnf
    regexp="bind-address(.)+"
    line="bind-address = 0.0.0.0"
  become: yes
